### ISSUE TITLE
[질문] Template의 역할

### ISSUE THREAD

**Issue by woohyun-park** [VictoryJu/wanted-pre-onboarding-frontend#1]
## src/components/Template의 역할

src/components/Organism에서 사실상 해당 컴포넌트의 모든 기능과 뷰를 구현하고 있는것으로 보여지는데, 따로 Template/Todo에 TodoTemplate을 만들어서 바로 TodoList를 반환하는 이유가 무엇인가요? 어떤 이점이 있어서 이렇게 구현하신건지 궁금합니다!

**Comment by VictoryJu** [comment]
@woohyun-park 안녕하세요 우현님 리뷰 감사드립니다!

본래 구현하고자했던것이
atomic 패턴을 사용해서
Organism에서 TodoList의 데이터를 받아오고 받아온 데이터를
Molecules의 TodoItem으로 넘기는 방식으로 구현하고
Template는 Organism들을 묶어서 하나의 컴포넌트로 만들고싶었습니다. (현재는 TodoList밖에없지만 사이즈가 커질 가능성을 대비하여)

pages에서는 url에따라 template로 컴포넌트를 보여주는 기능만 처리 하기위해 구조를 설계했었지만
시간부족으로 Organism에서 모든 기능을 처리하였습니다 현재 코드에서는 나누는게 의미가 없어져버렸네요

이렇게 구현하였을때 이점은 pages에서는 기능을 신경쓰지않고 보여주고자 하는 컴포넌트들을 template로 보여주면되고
components폴더들의 각 컴포넌트들은 비즈니스로직을 담당해서 관심사가 분리되는 이점이 있다고 생각합니다.

**Comment by woohyun-park** [comment]
아하 atomic 패턴을 구현하기 위해서 만들어진 컴포넌트군요! atomic 패턴과 관심사 분리에 대해서도 더 공부해봐야겠네요 ...

답변 감사합니다!
