### ISSUE TITLE
아토믹 디자인 패턴

### ISSUE THREAD

**Issue by Kal-MH** [VictoryJu/wanted-pre-onboarding-frontend#2]
안녕하세요 승주님:)

개인적으로 아토믹 디자인을 명확하게 잡고 구현하신 분은 처음 본 거 같습니다. 비록 세세하게 컴포넌트를 파편화해서 나눈 것은 아니지만 개략적인 디자인 패턴 적용에 대해서 생각해볼 수 있었어요

Router도 따로 모듈로 관리해서 사용하니까 확실히 App.tsx가 깔끔해지는 거 같습니다(저도 나중에 적용해봐야겠습니다:))

**Comment by VictoryJu** [comment]
@Kal-MH  안녕하세요 미현님!

아토믹패턴을 제대로 적용시키지 못했지만,, 좋은 리뷰 남겨주셔서 감사합니다😊
나중에 해당부분은 리팩토링해서 다시 작성해보겠습니다 :)
